### ISSUE TITLE
wormholelabs.xyz vs wormhole.com

### ISSUE THREAD

**Issue by erikcasson** [wormholelabs-xyz/wormholelabs.xyz#1]
Which is real site of Wormhole foundation?
Wormhole.com seems to be real website of Wormhole foundation. But wormholelabs.xyz is not.
What is wormholelabs.xyz?

**Comment by tonyjin** [comment]
Wormhole Foundation's website is here: https://wormhole.foundation/
They maintain the website of the Wormhole protocol: https://wormhole.com/

Wormhole Labs is an independent technology company and this is the repo for our website.
